In [1]:
import pandas as pd

1. Load the dataset

- Use pandas to read the CSV file.

- Display the first 5 rows of the dataset.

- Use .info() and .describe() to profile the data.

In [ ]:
housing_data = pd.read_csv("Nashville_housing_data.csv")
housing_data[:5]

,Unnamed: 0.1,Unnamed: 0,Parcel ID,Land Use,Property Address,Suite/ Condo #,Property City,Sale Date,Sale Price,Legal Reference,...,Building Value,Total Value,Finished Area,Foundation Type,Year Built,Exterior Wall,Grade,Bedrooms,Full Bath,Half Bath
0,0,0,105 03 0D 008.00,RESIDENTIAL CONDO,1208 3RD AVE S,8,NASHVILLE,2013-01-24,132000,20130128-0008725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,105 11 0 080.00,SINGLE FAMILY,1802 STEWART PL,NaN,NASHVILLE,2013-01-11,191500,20130118-0006337,...,134400.0,168300.0,1149.00000,PT BSMT,1941.0,BRICK,C,2.0,1.0,0.0
2,2,2,118 03 0 130.00,SINGLE FAMILY,2761 ROSEDALE PL,NaN,NASHVILLE,2013-01-18,202000,20130124-0008033,...,157800.0,191800.0,2090.82495,SLAB,2000.0,BRICK/FRAME,C,3.0,2.0,1.0
3,3,3,119 01 0 479.00,SINGLE FAMILY,224 PEACHTREE ST,NaN,NASHVILLE,2013-01-18,32000,20130128-0008863,...,243700.0,268700.0,2145.60001,FULL BSMT,1948.0,BRICK/FRAME,B,4.0,2.0,0.0
4,4,4,119 05 0 186.00,SINGLE FAMILY,316 LUTIE ST,NaN,NASHVILLE,2013-01-23,102000,20130131-0009929,...,138100.0,164800.0,1969.00000,CRAWL,1910.0,FRAME,C,2.0,1.0,0.0

In [7]:
housing_data.info()
housing_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56636 entries, 0 to 56635
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0.1                       56636 non-null  int64
 1   Unnamed: 0                         56636 non-null  int64
 2   Parcel ID                          56636 non-null  object
 3   Land Use                           56636 non-null  object
 4   Property Address                   56477 non-null  object
 5   Suite/ Condo   #                   6109 non-null   object
 6   Property City                      56477 non-null  object
 7   Sale Date                          56636 non-null  object
 8   Sale Price                         56636 non-null  int64
 9   Legal Reference                    56636 non-null  object
 10  Sold As Vacant                     56636 non-null  object
 11  Multiple Parcels Involved in Sale  56636 non-null  object
 12  Owner Name                         25261 non-null  object
 13  Address                            26017 non-null  object
 14  City                               26017 non-null  object
 15  State                              26017 non-null  object
 16  Acreage                            26017 non-null  float64
 17  Tax District                       26017 non-null  object
 18  Neighborhood                       26017 non-null  float64
 19  image                              25335 non-null  object
 20  Land Value                         26017 non-null  float64
 21  Building Value                     26017 non-null  float64
 22  Total Value                        26017 non-null  float64
 23  Finished Area                      24166 non-null  float64
 24  Foundation Type                    24164 non-null  object
 25  Year Built                         24165 non-null  float64
 26  Exterior Wall                      24165 non-null  object
 27  Grade                              24165 non-null  object
 28  Bedrooms                           24159 non-null  float64
 29  Full Bath                          24277 non-null  float64
 30  Half Bath                          24146 non-null  float64
dtypes: float64(10), int64(3), object(18)
memory usage: 13.4+ MB

,Unnamed: 0.1,Unnamed: 0,Sale Price,Acreage,Neighborhood,Land Value,Building Value,Total Value,Finished Area,Year Built,Bedrooms,Full Bath,Half Bath
count,56636.00000,56636.00000,5.663600e+04,26017.000000,26017.000000,2.601700e+04,2.601700e+04,2.601700e+04,24166.000000,24165.000000,24159.000000,24277.000000,24146.000000
mean,28317.50000,28317.50000,3.272111e+05,0.498903,4356.215782,6.907267e+04,1.608025e+05,2.323971e+05,1926.954345,1963.749224,3.090029,1.886106,0.283981
std,16349.54926,16349.54926,9.287425e+05,1.570396,2170.348270,1.060405e+05,2.068041e+05,2.810703e+05,1687.017313,26.546141,0.852942,0.961572,0.487905
min,0.00000,0.00000,5.000000e+01,0.010000,107.000000,1.000000e+02,0.000000e+00,1.000000e+02,0.000000,1799.000000,0.000000,0.000000,0.000000
25%,14158.75000,14158.75000,1.350000e+05,0.180000,3126.000000,2.100000e+04,7.590000e+04,1.028000e+05,1239.000000,1948.000000,3.000000,1.000000,0.000000
50%,28317.50000,28317.50000,2.054500e+05,0.270000,3929.000000,2.880000e+04,1.114000e+05,1.485000e+05,1632.000000,1960.000000,3.000000,2.000000,0.000000
75%,42476.25000,42476.25000,3.290000e+05,0.450000,6228.000000,6.000000e+04,1.807000e+05,2.685000e+05,2212.000000,1983.000000,3.000000,2.000000,1.000000
max,56635.00000,56635.00000,5.427806e+07,160.060000,9530.000000,2.772000e+06,1.297180e+07,1.394040e+07,197988.000000,2017.000000,11.000000,10.000000,3.000000

2. Standardize Headings

Change all column headings to be all lower-case lettering. If a column heading has two or more words, then connect each word using "_".  For example, "Column Heading" would become "column_heading".

In [ ]:
housing_data.columns = housing_data.columns.str.lower().str.replace(" ", "_")

Index(['unnamed:_0.1', 'unnamed:_0', 'parcel_id', 'land_use',
       'property_address', 'suite/_condo___#', 'property_city', 'sale_date',
       'sale_price', 'legal_reference', 'sold_as_vacant',
       'multiple_parcels_involved_in_sale', 'owner_name', 'address', 'city',
       'state', 'acreage', 'tax_district', 'neighborhood', 'image',
       'land_value', 'building_value', 'total_value', 'finished_area',
       'foundation_type', 'year_built', 'exterior_wall', 'grade', 'bedrooms',
       'full_bath', 'half_bath'],
      dtype='object')

3. Eliminate Unneeded Columns

Eliminate columns we don't need: unnamed_0.1 and unnamed_0.

In [ ]:
housing_data = housing_data.drop(columns=["unnamed:_0.1", "unnamed:_0"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56636 entries, 0 to 56635
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   parcel_id                          56636 non-null  object
 1   land_use                           56636 non-null  object
 2   property_address                   56477 non-null  object
 3   suite/_condo___#                   6109 non-null   object
 4   property_city                      56477 non-null  object
 5   sale_date                          56636 non-null  object
 6   sale_price                         56636 non-null  int64
 7   legal_reference                    56636 non-null  object
 8   sold_as_vacant                     56636 non-null  object
 9   multiple_parcels_involved_in_sale  56636 non-null  object
 10  owner_name                         25261 non-null  object
 11  address                            26017 non-null  object
 12  city                               26017 non-null  object
 13  state                              26017 non-null  object
 14  acreage                            26017 non-null  float64
 15  tax_district                       26017 non-null  object
 16  neighborhood                       26017 non-null  float64
 17  image                              25335 non-null  object
 18  land_value                         26017 non-null  float64
 19  building_value                     26017 non-null  float64
 20  total_value                        26017 non-null  float64
 21  finished_area                      24166 non-null  float64
 22  foundation_type                    24164 non-null  object
 23  year_built                         24165 non-null  float64
 24  exterior_wall                      24165 non-null  object
 25  grade                              24165 non-null  object
 26  bedrooms                           24159 non-null  float64
 27  full_bath                          24277 non-null  float64
 28  half_bath                          24146 non-null  float64
dtypes: float64(10), int64(1), object(18)
memory usage: 12.5+ MB

4. Handle missing values
Drop all rows where the sale_price column is missing.

Fill missing values in the Bedrooms column with the median number of bedrooms.

In [10]:
housing_data = housing_data.dropna(subset=['sale_price'])
housing_data['bedrooms'] = housing_data['bedrooms'].fillna(housing_data['bedrooms'].median())

5. Fix column data types
Convert the sale_date column to datetime format using pd.to_datetime().

In [ ]:
housing_data['sale_date'] = pd.to_datetime(housing_data['sale_date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56636 entries, 0 to 56635
Data columns (total 29 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   parcel_id                          56636 non-null  object
 1   land_use                           56636 non-null  object
 2   property_address                   56477 non-null  object
 3   suite/_condo___#                   6109 non-null   object
 4   property_city                      56477 non-null  object
 5   sale_date                          56636 non-null  datetime64[ns]
 6   sale_price                         56636 non-null  int64
 7   legal_reference                    56636 non-null  object
 8   sold_as_vacant                     56636 non-null  object
 9   multiple_parcels_involved_in_sale  56636 non-null  object
 10  owner_name                         25261 non-null  object
 11  address                            26017 non-null  object
 12  city                               26017 non-null  object
 13  state                              26017 non-null  object
 14  acreage                            26017 non-null  float64
 15  tax_district                       26017 non-null  object
 16  neighborhood                       26017 non-null  float64
 17  image                              25335 non-null  object
 18  land_value                         26017 non-null  float64
 19  building_value                     26017 non-null  float64
 20  total_value                        26017 non-null  float64
 21  finished_area                      24166 non-null  float64
 22  foundation_type                    24164 non-null  object
 23  year_built                         24165 non-null  float64
 24  exterior_wall                      24165 non-null  object
 25  grade                              24165 non-null  object
 26  bedrooms                           56636 non-null  float64
 27  full_bath                          24277 non-null  float64
 28  half_bath                          24146 non-null  float64
dtypes: datetime64[ns](1), float64(10), int64(1), object(17)
memory usage: 12.5+ MB